name: barreler
description: A library for generating barrel files.
version: 1.0.1
homepage: https://github.com/mrgnhnt96/barreler
topics:
  - barrel
  - library-generator
  - code-gen
  - generation

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ">=2.0.0 <3.0.0"
  autoequal: ">=0.0.1 <1.0.0"
  checked_yaml: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  equatable: ">=2.0.0 <3.0.0"
  file: ">=6.1.4 <8.0.0"
  glob: ">=2.0.0 <3.0.0"
  json2yaml: ">=3.0.0 <4.0.0"
  json_annotation: ">=4.0.0 <5.0.0"
  mason_logger: ">=0.0.1 <1.0.0"
  path: ">=1.0.0 <2.0.0"
  pub_updater: ^0.4.0
  yaml: ">=3.0.0 <4.0.0"

dev_dependencies:
  autoequal_gen: ^0.9.1
  build_runner: ^2.3.3
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  pana: ^0.22.2
  test: ^1.21.6
  very_good_analysis: ^5.1.0

executables:
  barreler:
